# Script to generate PhyloTree visualization result
## Using R package ggtree instead of iTOL since iTOL only has 
## website version (batch mode needs subscription)

# Load packages
library(ggplot2)
library(ggtree)
library(ggnewscale)

# Pass parameters
args <- commandArgs(trailingOnly=TRUE)
nwk_tree_input <- args[1]
lineage_input <- args[2]
dr_cat_input <- args[3]
dr_indiv_input <- args[4]
png_output <- args[5]
pdf_output <- args[6]

# 1. Read Newick tree file which is generated by RAxML
tree <- read.tree(nwk_tree_input)
data <- fortify(tree)

# 2. Construct basic tree
treegraph =
  # tree：treefile, shape, size, color
  #ggtree(tree, layout="rectangular", size=0.8, col="deepskyblue3") +
  ggtree(tree, layout="rectangular", size=0.7) +
  # tip label：size, color, height
  geom_tiplab(size=3, align=TRUE) +
  # tip point：size, color
  #geom_tippoint(size=1.5, color="deepskyblue3") +
  # node point：color, alpha, size
  #geom_nodepoint(color="orange", alpha=1/4, size=2) +
  # tree scale
  geom_treescale(x=0, y=0) +
  # put root node on the upper left
  scale_y_reverse() + 
  # root edge
  #geom_rootedge(rootedge=0.001, size=0.8, col="deepskyblue3")
  geom_rootedge(rootedge=0.001, size=0.8)

# 3. Add annotation

# 3.1 lineage
lineage_df <- read.table(lineage_input, header=TRUE, row.names=1,
                         sep='\t', comment.char="")[2]

# extract all lineage values
all_lineage <- sort(as.character(unique(lineage_df$lineage)))

lineage_list <- list()

for (lin in all_lineage)
{
  lin_sample <- rownames(lineage_df)[lineage_df$lineage==lin]
  lineage_list <- append(lineage_list, list(lin_sample))
}

names(lineage_list) <- all_lineage

# use groupOTU() to separate lineages based on different colors
p1 <- groupOTU(treegraph, lineage_list, 'Lineage') + 
  aes(color=Lineage) +
  scale_color_brewer(limits=all_lineage, palette = "Dark2") +
  theme(legend.position="right")

# 3.2 dr_cat: drug resistance category
dr_cat_df <- read.table(dr_cat_input, header=TRUE, row.names=1,
                       sep='\t', comment.char="")[2]

# dr_cat_df$dr_cat <- factor(dr_cat_df$dr_cat,
#                            levels = c("Sensitive", "Other",
#                                       "Pre-MDR", "MDR",
#                                       "Pre-XDR", "XDR"))
dr_cat_order <- c("Sensitive", "RR-TB", "HR-TB", "MDR-TB","Pre-XDR-TB", "XDR-TB", "Other")
dr_cat_values <- unique(dr_cat_df$dr_cat)
dr_cat_levels <- dr_cat_order[dr_cat_order %in% dr_cat_values]
dr_cat_df$dr_cat <- factor(dr_cat_df$dr_cat,
                           levels = dr_cat_levels)

# use gheatmap() to add drug resistance category info
p2 <- gheatmap(p1, dr_cat_df, offset=0.028, width=0.04,
               colnames_angle=30, hjust=0, font.size=3) +
  scale_fill_brewer(#palette = "YlOrRd",
                    palette="Paired",
                    name="Drug resistance\ncategory",
                    limits=dr_cat_levels) +
  guides(fill=guide_legend(title="Drug resistance\ncategory")) +
  theme(legend.position="right")


# 3.3 dr_indiv

dr_indiv_df <- read.table(dr_indiv_input, header=TRUE, 
                          row.names=1, sep='\t')
index <- 1:ncol(dr_indiv_df)
dr_indiv_df[, index] <- lapply(dr_indiv_df[, index], as.factor) 




# use gheatmap() to add individual drug resistance info

p3 <- p2 + new_scale_fill()

gheatmap(p3, dr_indiv_df, offset=0.036, width=0.6, colnames_angle=30, hjust=0, font.size=3) +
  #scale_fill_manual(values=c("grey","#33A02C"))+
  scale_fill_manual(values=c("grey","#3a3a3a"))+
  guides(fill=F)


# 4. Export results

#ggsave(pdf_output, device="pdf", width = 31, height = 21, units = "cm")
#ggsave(png_output, device="png", width = 31, height = 21, units = "cm")

ggsave(pdf_output, device="pdf", width=33, height=21, units="cm", dpi=1500)
ggsave(png_output, device="png", width=33, height=21, units="cm", dpi=1500)








